# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15j8YA1XFrjpcYGl_v1R9bWpkGtSV-VC3
"""

# streamlit_app.py - Streamlit 대시보드

import streamlit as st
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import time
import re
from typing import Dict, Tuple

# ========================================
# 페이지 설정
# ========================================

st.set_page_config(
    page_title="EXAONE 1.2B LLM 대시보드",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# 커스텀 CSS
st.markdown("""
<style>
    .main {
        background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
    }
    .stButton > button {
        background: linear-gradient(135deg, #38bdf8 0%, #0284c7 100%);
        color: white;
        border: none;
        border-radius: 8px;
        font-weight: 600;
        padding: 10px 24px;
    }
    .stButton > button:hover {
        background: linear-gradient(135deg, #0284c7 0%, #0166aa 100%);
    }
    .message-user {
        background: #38bdf8;
        color: #0f172a;
        padding: 12px 16px;
        border-radius: 8px;
        margin: 8px 0;
        max-width: 70%;
        margin-left: auto;
    }
    .message-assistant {
        background: rgba(56, 189, 248, 0.15);
        color: #cbd5e1;
        border-left: 3px solid #38bdf8;
        padding: 12px 16px;
        border-radius: 8px;
        margin: 8px 0;
        max-width: 85%;
    }
</style>
""", unsafe_allow_html=True)

# ========================================
# 1. 모델 로드 (캐싱)
# ========================================

@st.cache_resource
def load_model():
    """모델 로드 (한 번만 실행)"""

    MODEL_PATH = "/content/drive/MyDrive/exaone4_gsm8k2"
    BASE_MODEL = "LGAI-EXAONE/EXAONE-4.0-1.2B"

    st.info("🚀 모델을 로드 중입니다... 첫 실행은 1-2분 소요됩니다.")

    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True
    )
    base_tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)

    try:
        from transformers.trainer_utils import get_last_checkpoint
        last_ckpt = get_last_checkpoint(MODEL_PATH)
        lora_model = PeftModel.from_pretrained(base_model, last_ckpt)
        model = lora_model
    except:
        st.warning("⚠️ LoRA 로드 실패, 베이스 모델 사용")
        model = base_model

    model.eval()
    return model, base_tokenizer

# ========================================
# 2. 헬퍼 함수
# ========================================

def extract_math_answer(text: str) -> str:
    """####로 구분된 수학 답 추출"""
    if "####" in text:
        answer_part = text.split("####")[-1].strip()
        numbers = re.findall(r"\d+", answer_part)
        return numbers[0] if numbers else answer_part[:50]
    numbers = re.findall(r"\d+", text)
    return numbers[-1] if numbers else "답을 찾을 수 없음"

def generate_response(
    model,
    tokenizer,
    prompt: str,
    max_length: int = 256,
    temperature: float = 0.7,
    top_p: float = 0.9
) -> Tuple[str, float]:
    """모델 추론"""

    start_time = time.time()

    chat = [{'role': 'user', 'content': prompt}]
    formatted_prompt = tokenizer.apply_chat_template(
        chat,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt",
        truncation=True,
        max_length=1024
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_length,
            temperature=temperature,
            top_p=top_p,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(
        outputs[0][inputs.input_ids.shape[1]:],
        skip_special_tokens=True
    )

    processing_time = time.time() - start_time
    return response.strip(), processing_time

# ========================================
# 3. Streamlit 레이아웃
# ========================================

st.markdown("""
# 🤖 EXAONE 1.2B LLM 대시보드
### LoRA 경량화 모델 - 실시간 채팅 & 수학 튜터
""")

with st.sidebar:
    st.markdown("## ⚙️ 설정")

    mode = st.radio(
        "📌 모드 선택",
        ["일반 채팅", "수학 풀이"],
        key="mode_selector"
    )

    st.markdown("---")
    st.markdown("## 🎛️ 모델 파라미터")

    temperature = st.slider(
        "🌡️ Temperature (창의성)",
        0.1, 2.0, 0.7, 0.1,
        help="낮을수록 일관성 있음, 높을수록 창의적"
    )

    top_p = st.slider(
        "🎯 Top-P (다양성)",
        0.1, 1.0, 0.9, 0.05,
        help="확률이 높은 토큰만 선택"
    )

    max_length = st.slider(
        "📏 최대 길이",
        50, 512, 256, 50,
        help="생성할 토큰의 최대 개수"
    )

    st.markdown("---")

    st.markdown("## 📊 모델 정보")
    col1, col2 = st.columns(2)
    with col1:
        st.metric("모델", "EXAONE 1.2B")
        st.metric("양자화", "4-bit NF4")
    with col2:
        st.metric("LoRA 파라미터", "1.6M")
        st.metric("효율성", "99.1% ↓")

    if torch.cuda.is_available():
        memory_used = torch.cuda.memory_allocated() / 1e9
        memory_total = torch.cuda.get_device_properties(0).total_memory / 1e9
        st.metric("GPU 메모리", f"{memory_used:.2f}/{memory_total:.2f} GB")

tab1, tab2, tab3 = st.tabs(["💬 채팅", "📈 통계", "📚 샘플"])

with tab1:
    st.markdown("### 챗봇과 대화하세요")

    if "messages" not in st.session_state:
        st.session_state.messages = []
    if "model" not in st.session_state:
        st.session_state.model, st.session_state.tokenizer = load_model()
        st.success("✅ 모델 로드 완료!")

    model = st.session_state.model
    tokenizer = st.session_state.tokenizer

    chat_container = st.container()
    with chat_container:
        for msg in st.session_state.messages:
            if msg["role"] == "user":
                st.markdown(f"""
                <div class="message-user">
                    <strong>👤 You:</strong><br>{msg["content"]}
                </div>
                """, unsafe_allow_html=True)
            else:
                st.markdown(f"""
                <div class="message-assistant">
                    <strong>🤖 Assistant:</strong><br>{msg["content"]}
                </div>
                """, unsafe_allow_html=True)

    st.markdown("---")
    col1, col2 = st.columns([4, 1])

    with col1:
        user_input = st.text_input(
            "메시지를 입력하세요:",
            placeholder="예: 2 + 2는 몇이야? / 한국의 수도는 어디야?",
            key="user_input"
        )

    with col2:
        send_button = st.button("전송", use_container_width=True)

    if send_button and user_input:
        st.session_state.messages.append({"role": "user", "content": user_input})

        with st.spinner("🤔 응답 생성 중..."):
            if "수학" in mode:
                system_prompt = """수학 문제를 단계별로 풀어주세요.
각 단계를 명확히 설명하고,
최종 답은 #### 뒤에 숫자만 적어주세요."""
                full_prompt = f"{system_prompt}\n\n질문: {user_input}"
            else:
                full_prompt = user_input

            response, processing_time = generate_response(
                model,
                tokenizer,
                full_prompt,
                max_length=max_length,
                temperature=temperature,
                top_p=top_p
            )

            st.session_state.messages.append({"role": "assistant", "content": response})

            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("응답 길이", f"{len(response)} 자")
            with col2:
                st.metric("처리 시간", f"{processing_time:.2f}초")
            with col3:
                if "수학" in mode:
                    answer = extract_math_answer(response)
                    st.metric("추출된 답", answer)

        st.rerun()

    if not st.session_state.messages:
        st.info("""
        👋 **EXAONE 1.2B에 오신 것을 환영합니다!**

        - **일반 채팅**: 자유로운 대화 (한국어)
        - **수학 풀이**: 수학 문제 단계별 풀이

        궁금한 점을 입력해보세요!
        """)

with tab2:
    st.markdown("### 📊 모델 성능 지표")

    if st.session_state.messages:
        assistant_messages = [m for m in st.session_state.messages if m["role"] == "assistant"]
        user_messages = [m for m in st.session_state.messages if m["role"] == "user"]

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric("총 대화 수", len(st.session_state.messages) // 2)
        with col2:
            avg_response_length = sum(len(m["content"]) for m in assistant_messages) / len(assistant_messages) if assistant_messages else 0
            st.metric("평균 응답 길이", f"{int(avg_response_length)} 자")
        with col3:
            total_chars = sum(len(m["content"]) for m in assistant_messages)
            st.metric("총 생성 문자", f"{total_chars:,} 자")
        with col4:
            st.metric("사용자 입력", f"{len(user_messages)}")

        st.markdown("---")

        st.markdown("### 📈 응답 길이 분포")
        response_lengths = [len(m["content"]) for m in assistant_messages]

        col1, col2 = st.columns(2)
        with col1:
            st.line_chart(response_lengths, use_container_width=True)
        with col2:
            import statistics
            st.metric("최소", min(response_lengths))
            st.metric("최대", max(response_lengths))
            st.metric("평균", f"{statistics.mean(response_lengths):.0f}")
            st.metric("중앙값", f"{statistics.median(response_lengths):.0f}")
    else:
        st.info("📌 아직 메시지가 없습니다. 채팅 탭에서 시작해보세요!")

with tab3:
    st.markdown("### 📚 사용 예시")

    st.markdown("#### 🧮 수학 풀이 예시")
    sample_math_problems = [
        "철수는 사과 12개를 가지고 있습니다. 영희에게 5개를 주었습니다. 철수에게 남은 사과는 몇 개인가요?",
        "한 반에 학생이 24명입니다. 남학생이 여학생보다 4명 더 많습니다. 여학생은 몇 명인가요?",
        "상자에 빨간 공 15개, 파란 공 20개가 있습니다. 전체 공은 몇 개인가요?"
    ]

    for i, problem in enumerate(sample_math_problems, 1):
        if st.button(f"📝 예시 {i}: {problem[:40]}...", use_container_width=True):
            st.session_state.messages.append({"role": "user", "content": problem})
            st.rerun()

    st.markdown("---")
    st.markdown("#### 💬 일반 채팅 예시")
    sample_chat = [
        "안녕하세요! 당신은 누구인가요?",
        "한국의 수도는 어디인가요?",
        "오늘 날씨가 어때요?"
    ]

    for i, chat in enumerate(sample_chat, 1):
        if st.button(f"💬 예시 {i}: {chat}", use_container_width=True):
            st.session_state.messages.append({"role": "user", "content": chat})
            st.rerun()

st.markdown("---")
st.markdown("""
### 🎯 정보
- **모델**: EXAONE 4.0 1.2B (LoRA 경량화)
- **학습 데이터**: GSM8K-Ko (한국어 수학 문제)
- **프레임워크**: Streamlit + PyTorch + Hugging Face
- **최적화**: 4-bit Quantization + LoRA

💡 **팁**: 사이드바에서 모델 파라미터를 조정하여 응답 품질을 개선할 수 있습니다.
""")